# Generated by Django 4.1.5 on 2023-01-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adotar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoadocao',
            name='cidade',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoadocao',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoadocao',
            name='telefone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
